jdu211171/jduportfolio

- portfolio-server/src/config/kintoneConfig.js
- portfolio-server/src/controllers/kintoneController.js
- portfolio-server/src/services/kintoneService.js
- portfolio-server/src/services/studentService.js
3 methods have been updated so far
> kintone sync , get , post

- portfolio-client/src/components/Notification/Notifications.jsx
- portfolio-client/src/components/layout/Layout.jsx
- portfolio-client/src/locales/translations.js
- portfolio-server/portfolio2_dump.sql
- portfolio-server/src/controllers/draftController.js
> Changed to Japanese Language

- portfolio-server/package.json
- portfolio-server/src/controllers/authController.js
- portfolio-server/src/passport/google-strategy.js
- portfolio-server/src/routes/auth-route.js
- portfolio-server/src/services/authService.js
create following configures
GOOGLE_CLIENT_ID=your_google_client_id
GOOGLE_CLIENT_SECRET=your_google_client_secret_key
GOOGLE_CALLBACK_URL=http://localhost:8000/api/auth/google/callback
> Google Login

- .gitignore
- portfolio-client/src/pages/GoogleAuthCallback.jsx
- portfolio-client/src/pages/Login/Login.jsx
- portfolio-client/src/routes.jsx
- portfolio-server/src/controllers/authController.js
- portfolio-server/src/passport/google-strategy.js
- portfolio-server/src/routes/auth-route.js
> solved Implement Google authentication flow with callback handling

- portfolio-server/package.json
- portfolio-server/src/controllers/studentController.js
- portfolio-server/src/services/cronService.js
- portfolio-server/src/services/studentService.js
- portfolio-server/src/utils/emailService.js
- portfolio-server/src/utils/emailToStaff.js
- portfolio-server/src/utils/emailToStudent.js
> 115 send email even if semester is below 7

- portfolio-client/src/assets/icons/menuIcon.svg
- portfolio-client/src/components/Layout/Layout.jsx
- portfolio-client/src/components/Layout/Layout.module.css
- portfolio-server/src/passport/google-strategy.js
> fixed sidebar and language switcher

- portfolio-client/deploy.sh
- portfolio-client/src/components/Table/Avatar/UserAvatar.module.css
Ensures consistent SSH key validation on macOS or Linux, references script location for more robust deployment, and introduces a new layout for improved user avatar styling
> **Refines key checks, path logic, and avatar style**

- portfolio-client/src/components/CreditsProgressBar/CreditsProgressBar.jsx
- portfolio-client/src/components/CreditsProgressBar/CreditsProgressBar.module.css
- portfolio-client/src/components/Deliverables/Deliverables.jsx
- portfolio-client/src/components/Deliverables/Deliverables.module.css
- portfolio-client/src/components/SkillSelector/SkillSelector.module.css
- portfolio-client/src/locales/translations.js
- portfolio-client/src/pages/Profile/StudentProfile/StudentProfile.jsx
- portfolio-client/src/pages/Profile/StudentProfile/StudentProfile.module.css
- portfolio-client/src/pages/Profile/Top/Top.jsx
- portfolio-client/src/pages/Profile/Top/Top.module.css
- Enhanced the Deliverables component to support adding, editing, and deleting deliverables with a more structured form.
- Implemented image upload functionality with previews for deliverables.
- Added reset functionality for image previews when editing.
- Improved styling for the Deliverables and SkillSelector components for better user experience.
- Updated translations to include student credits in multiple languages.
- Refactored the StudentProfile and Top components for cleaner code and better organization.
- Added a credits progress bar to visualize student credits based on selected university.
> Refactor Deliverables component for improved functionality and UI

- portfolio-client/src/pages/ChekProfile/ChekProfile.jsx
- portfolio-client/src/pages/Profile/Stats/Stats.jsx
- portfolio-client/src/pages/Student/Student.jsx
- portfolio-server/src/controllers/studentController.js
> updated student profile

- portfolio-client/src/pages/Profile/QA/QA.jsx
- portfolio-client/src/pages/Setting/Setting.jsx
> fixed student page  bugs

- portfolio-server/src/controllers/draftController.js
- portfolio-server/src/services/studentService.js
> fixed credit bugs

- portfolio-client/src/pages/Profile/QA/QA.jsx
- portfolio-client/src/pages/Profile/Top/Top.jsx
> fixed qa bugs

- portfolio-server/migrations/20250707065147-add-previous-profile-data-to-drafts.js
- portfolio-server/migrations/20250707091832-add-changed-fields-to-drafts.js
- portfolio-server/package.json
- portfolio-server/src/controllers/draftController.js
- portfolio-server/src/models/Draft.js
- portfolio-server/src/routes/drafts-route.js
- portfolio-server/src/services/draftService.js
A New changes for Draft Control
> 171 new master for backend

- portfolio-server/migrations/20250714180941-create-it-skills-table.js
- portfolio-server/seeders/20250714183652-initial-it-skills.js
- portfolio-server/src/controllers/itSkillController.js
- portfolio-server/src/models/index.js
- portfolio-server/src/models/itskill.js
- portfolio-server/src/routes.js
- portfolio-server/src/routes/itSkillRoutes.js
- portfolio-server/src/services/itSkillService.js
a new changes for using by admin and staff
> a new changes for it skills

- portfolio-server/migrations/20250714180941-create-it-skills-table.js
- portfolio-server/migrations/20250715122907-add-furigana-to-admins.js
- portfolio-server/migrations/20250715122939-add-furigana-to-students.js
- portfolio-server/migrations/20250715122958-add-furigana-to-staff.js
- portfolio-server/migrations/20250715123014-add-furigana-to-recruiters.js
- portfolio-server/seeders/20250714183652-initial-it-skills.js
- portfolio-server/src/controllers/itSkillController.js
- portfolio-server/src/models/Admin.js
- portfolio-server/src/models/Recruiter.js
- portfolio-server/src/models/Staff.js
- portfolio-server/src/models/Student.js
- portfolio-server/src/models/index.js
- portfolio-server/src/models/itskill.js
- portfolio-server/src/routes.js
- portfolio-server/src/routes/itSkillRoutes.js
- portfolio-server/src/services/adminService.js
- portfolio-server/src/services/itSkillService.js
- portfolio-server/src/services/recruiterService.js
- portfolio-server/src/services/studentService.js
> 208 a new changes for it skills

- portfolio-client/src/pages/Profile/QA/QA.jsx
- portfolio-client/src/pages/Profile/Top/Top.jsx
- portfolio-server/src/controllers/qaController.js
> fixed bugs

- portfolio-client/src/components/CreditsProgressBar/CreditsProgressBar.jsx
- portfolio-client/src/components/SkillSelector/SkillSelector.jsx
- portfolio-client/src/components/Table/Table.jsx
- portfolio-client/src/pages/ChekProfile/ChekProfile.jsx
- portfolio-client/src/pages/CreditDetails/CreditDetails.jsx
- portfolio-client/src/pages/Profile/CompanyProfile/CompanyProfile.jsx
- portfolio-client/src/pages/Profile/QA/QA.jsx
- portfolio-client/src/pages/Profile/Stats/Stats.jsx
- portfolio-client/src/pages/Profile/StudentProfile/StudentProfile.jsx
- portfolio-client/src/pages/Profile/Top/Top.jsx
- portfolio-client/src/pages/Setting/Setting.jsx
- portfolio-client/src/pages/Student/Student.jsx
> clean code for no need console logs

- portfolio-client/src/pages/CreditDetails/CreditDetails.jsx
- portfolio-client/src/pages/Profile/Stats/Stats.jsx
- portfolio-client/src/pages/Profile/Top/Top.jsx
- portfolio-server/src/middlewares/recruiter-validation.js
> disabled student credits table and fixed recruiter profile errors

- portfolio-server/migrations/20250727074532-create-skills-table.js
- portfolio-server/migrations/20250727080143-add-other-skills-to-students.js
- portfolio-server/seeders/20250727074628-initial-skills.js
- portfolio-server/src/controllers/skillController.js
- portfolio-server/src/controllers/studentController.js
- portfolio-server/src/models/Student.js
- portfolio-server/src/models/index.js
- portfolio-server/src/models/skill.js
- portfolio-server/src/routes.js
- portfolio-server/src/routes/skillRoutes.js
- portfolio-server/src/services/skillService.js
Update other_skills field and new skills feature
> Update other_skills field and new skills feature

- portfolio-client/src/pages/Profile/Top/Top.jsx
> fixed qualification bugs

- portfolio-server/src/controllers/deliverableController.js
- portfolio-server/src/controllers/draftController.js
- portfolio-server/src/controllers/studentController.js
- portfolio-server/src/routes.js
- portfolio-server/src/routes/deliverableRoutes.js
- portfolio-server/src/routes/drafts-route.js
- portfolio-server/src/routes/fileRecordRoute.js
- portfolio-server/src/routes/recruiterFileRoutes.js
- portfolio-server/src/services/deliverableService.js
- portfolio-server/src/services/draftService.js
- portfolio-server/src/services/studentService.js
- portfolio-server/src/utils/storageService.js
- portfolio-server/src/utils/storageService.local.js
- portfolio-server/src/utils/storageService.s3.js
New sorting feature for the student model and new logic for staff to move drafts to approved status and send emails at the same time
> 269 new feature for student filter

- portfolio-server/src/services/deliverableService.js
> update deliverable function
